### ISSUE TITLE
Fabric ModLoader 14.8 Not Supported for 1.18.1

### ISSUE THREAD

**Issue by BearfootNick** [Gunpowder-MC/Gunpowder#133] opened 2022-07-12 06:32 UTC
**Information**
- Minecraft Version: 1.18.1
- Fabric API Version: 46.6
- OS: Clientside - Windows/Serverside Linux I think
- Other installed mods: Mods listed in startup logs

**Describe the issue**
Gunpowder Crashes on Startup with the 14.8 mod loader version for fabric 1.18.1

**Crash/Error logs**
[2022-07-12-1.log](https://github.com/Gunpowder-MC/Gunpowder/files/9090100/2022-07-12-1.log)

**To Reproduce**
1. Startup a server with the 14.8 Mod loader version
2. Watch Crash

**Expected behavior**
I expected the server to start after updating the server jar and modloader version

**Additional context**
Seems to be calling for the wrong mod loader? Not an expert.
My server members are crafting pitchforks as we speak please update this for my safety lol

**Comment by Martmists-GH** [comment] 2022-07-12 10:48
It looks like newer versions of fabric removed `KnotClassLoader.addURL`.

I'm currently working on a complete rewrite of Gunpowder, but that will only be released for 1.18.2 and 1.19+, so you will have to downgrade your version of Fabric Loader for 1.18.1

**Comment by Martmists-GH** [comment] 2022-07-12 10:50
Closing as duplicate of #131

**Closed by Martmists-GH** 2022-07-12 10:50 UTC
