### ISSUE TITLE
1.16.2 Server crash on village generation

### ISSUE THREAD

**Issue by Katorone** [Gunpowder-MC/Gunpowder#78] opened 2020-08-16 01:54 UTC
**Information**
- Minecraft Version: 1.16.2
- Fabric API Version: 0.18.0+build.397-1.16
- Gunpowder 0.2.9+1.16.2
- OS: Debian
- Other installed mods: Gunpowder SleepVote 1.0.0+gunpowder.0.2.9.mc.1.16.2

**Describe the issue**
When going near this village, the server crashes.  I have no idea what makes this village special, but the crash only happens when Gunpowder is loaded.

**Crash/Error logs**
https://pastebin.com/5v6xS8sG

**To Reproduce**
1. Create a world with the seed 868792932314998321
2. Go to -750 270
3. Server crashes

**Comment by martmists** [comment] 2020-08-16 02:45
Duplicate of https://github.com/Gunpowder-MC/GunpowderSleepVote/issues/1

**Comment by martmists** [comment] 2020-08-16 02:46
To add an update to this; It *should* be fixed in dev, we're awaiting feedback from testers to see if it works right now.

**Closed by martmists** 2020-08-16 02:45 UTC

**Comment by martmists** [comment] 2020-08-16 02:58
Fixed and pushed to CF

**Comment by Katorone** [comment] 2020-08-16 03:07
Can confirm that my world doesn't crash anymore in that location.
Thanks !
