### ISSUE TITLE
Freeze on SP world creation

### ISSUE THREAD

**Issue by Miss-Naru** [Gunpowder-MC/Gunpowder#119] opened 2021-07-30 19:59 UTC
**Information**
- Minecraft Version: 1.17.1
- Fabric API Version: 0.11.6
- OS: Linux Mint, Uma
- Other installed mods: Just Gunpowder(Base, Currency and Permissions) and it's Dependencies

**Describe the issue**
The error causes the game to freeze on SP world creation.

**Crash/Error logs**
https://github.com/Miss-Naru/Miss-Naru/blob/main/error1.log

**To Reproduce**
1. Install MC
2. Install Fabric
3. Add FabricAPI, FabricLanguageKoltin and Gunpowder(Base, Currency and Permissions) to the mods folder
4. Start the game and create a new SP world

**Expected behavior**
The game is supposed to create the new SP world.

**Comment by martmists-gh** [comment] 2021-07-30 20:07
> [21:38:09] [Gunpowder Database Thread/INFO]: [STDERR]: java.util.ServiceConfigurationError: org.slf4j.spi.SLF4JServiceProvider: org.apache.logging.slf4j.SLF4JServiceProvider not a subtype

Looks like an issue with your installation, as minecraft itself should be bundling SLF4J.

**Comment by Miss-Naru** [comment] 2021-07-30 20:09
> > [21:38:09] [Gunpowder Database Thread/INFO]: [STDERR]: java.util.ServiceConfigurationError: org.slf4j.spi.SLF4JServiceProvider: org.apache.logging.slf4j.SLF4JServiceProvider not a subtype
> 
> Looks like an issue with your installation, as minecraft itself should be bundling SLF4J.

**Comment by Miss-Naru** [comment] 2021-07-30 20:10
> > [21:38:09] [Gunpowder Database Thread/INFO]: [STDERR]: java.util.ServiceConfigurationError: org.slf4j.spi.SLF4JServiceProvider: org.apache.logging.slf4j.SLF4JServiceProvider not a subtype
> 
> I've seen this error before but I'm not quite sure what causes it, try asking in Fabricord maybe?

I posted on the Discord. Guess it's time to wait.

**Comment by martmists-gh** [comment] 2021-07-30 20:27
It happens to everyone, don't worry about it

**Comment by Martmists-GH** [comment] 2022-07-13 14:32
Closing as duplicate of #116

**Closed by Martmists-GH** 2022-07-13 14:32 UTC
